### ISSUE TITLE
api server 在rust desk 1.2.0版本失效

### ISSUE THREAD

**Issue by GMYXDS** [xiaoyi510/rustdesk-api-server#10]
在官方预发布的1.2.0版本中 https://github.com/rustdesk/rustdesk/releases/tag/nightly
这个接口好像失效了
看楼主能不能修复一下

他这个ui也进行了很大的调整

**Comment by GMYXDS** [comment]
1.2.0的api 已经搞定了，到时候整理下开源出来，他这个1.2.0 改了很多，而且代码还天天在变。但是UI变好看了，功能不是很稳定

**Comment by xiaoyi510** [comment]
我去看看预发布..他这个 1.1.9的这个API太拉了 我都没更新的动力

**Comment by GMYXDS** [comment]
> 我去看看预发布..他这个 1.1.9的这个API太拉了 我都没更新的动力

1.2.0也差不多，大的结构没有变

**Comment by xiaoyi510** [comment]
主要接口里面很多数据..他不处理
