### ISSUE TITLE
关于docker怎么跑起来

### ISSUE THREAD

**Issue by qq289531426** [xiaoyi510/rustdesk-api-server#12]
没有介绍docker容器怎么创建，怎么让容器跑起来，自己添加的都跑失败了

**Comment by xiaoyi510** [comment]
编译后把执行文件 copy到 docker 里面就行了

**Comment by xiaoyi510** [comment]
FROM alpine:3.15
RUN mkdir /app

# 复制配置文件
COPY conf /app/conf

# 复制主文件
COPY rustdesk-api-server /app
WORKDIR /app
ENTRYPOINT ["./rustdesk-api-server"]

# 导出端口号
EXPOSE [21114]


这个Dockerfile 仓库也有
