### ISSUE TITLE
1.1.9以上版本配置api服务器后用户登录后建立连接速度变慢，退出登录正常

### ISSUE THREAD

**Issue by wes1997** [xiaoyi510/rustdesk-api-server#13]
1.1.9以上版本加入了令牌加密，导致配置api服务器后 只要登录的客户端连接其他客户端建立连接的速度变慢，退出登录就恢复正常了

**Comment by zhangbo8418** [comment]
> 1.1.9以上版本加入了令牌加密，导致配置api服务器后 只要登录的客户端连接其他客户端建立连接的速度变慢，退出登录就恢复正常了

我都说了，Pro的服务器和开源版的服务器不同。。。哎。。。不要瞎鸡儿搞。。。跟api服务器没关系。。。

**Comment by zhangbo8418** [comment]
<img width="1439" alt="群晖套件" src="https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/cf483cce-b899-4868-a0d4-3c818cdab981">

<img width="1439" alt="群晖RustDesk服务器" src="https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/dd417fe4-bcd1-47ff-9682-13e56dd4d252">

<img width="1439" alt="API服务器" src="https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/2819fe87-8942-47d0-9cf6-4a9c7604d9b2">


地址簿功能演示

https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/73c371ca-4abf-4872-92be-e11023b8ee2b

**Comment by zhangbo8418** [comment]
> 1.1.9以上版本加入了令牌加密，导致配置api服务器后 只要登录的客户端连接其他客户端建立连接的速度变慢，退出登录就恢复正常了

经过你的神操作，最新版本RustDesk地址簿已经使用压缩了。。。我真特么谢谢你。。。

**Comment by wes1997** [comment]
这个开源的也是你搞的？ 当我没说 我研究研究自己改吧

**Comment by catbei2020** [comment]
@wes1997 帅锅，那个加载慢的问题解决了吗

**Comment by zhangbo8418** [comment]
> @wes1997 帅锅，那个加载慢的问题解决了吗

都说了那个是服务端问题，两个办法，1.自己修改开源服务端使它具有Pro付费服务端的功能。2.修改客户端，让它不使用Pro付费服务端的部分功能。

https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/b8e204c3-c3ab-40f4-88df-f7e52dc50fec

**Comment by wes1997** [comment]
> @wes1997帅锅，那个加载慢的问题解决了吗
@catbei2020 不用理他  他是官方的人， 说白了就是现在打算收费了 现在已经把收费功能都做出来了，用户功能就不想给人免费用，由于前期功能已经写完了已经开源，后期估计会把普通版本的用户功能给屏蔽的，我都在其他人的开源api 上回复官方都找过来喷了，你就明白了吧。

**Comment by zhangbo8418** [comment]
> > @wes1997帅锅，那个加载慢的问题解决了吗
> > @catbei2020 不用理他  他是官方的人， 说白了就是现在打算收费了 现在已经把收费功能都做出来了，用户功能就不想给人免费用，由于前期功能已经写完了已经开源，后期估计会把普通版本的用户功能给屏蔽的，我都在其他人的开源api 上回复官方都找过来喷了，你就明白了吧。

胡扯。。。我特么好心提醒，居然还被骂。。。你特么去看官方源码就知道了，明明是他并没有考虑开源版服务端的api功能，所以才导致的第三方api服务器登陆导致问题，登陆后客户端的请求是token加密去请求服务端，开源服务端没那功能不会返回数据所以一直等待，然后超时导致连接慢。。。

**Comment by xiaoyi510** [comment]
冲冲冲

**Comment by wes1997** [comment]
后面说的是最新版本的添加了压缩？ 单实际不影响， 其实主要是改了api获取列表的 post方法 改成了get方法，改完就能继续用

**Comment by zhangbo8418** [comment]
> 后面说的是最新版本的添加了压缩？ 单实际不影响， 其实主要是改了api获取列表的 post方法 改成了get方法，改完就能继续用

是的，但是你那次去折腾一番后他马上改了，我以为是针对这个，但是后面仔细看了是请求头加了压缩估计是解决请求数据太大问题的。。。

**Comment by KhyHolyDragon** [comment]
> > 后面说的是最新版本的添加了压缩？ 单实际不影响， 其实主要是改了api获取列表的 post方法 改成了get方法，改完就能继续用
> 
> 是的，但是你那次去折腾一番后他马上改了，我以为是针对这个，但是后面仔细看了是请求头加了压缩估计是解决请求数据太大问题的。。。

膜拜“裙下孤魂”大佬~~
