### ISSUE TITLE
dockercompose配置文件

### ISSUE THREAD

**Issue by mizb** [xiaoyi510/rustdesk-api-server#16]
大佬，有没有dockercompose配置参考，我应该映射什么路径，开什么端口，有什么环境需要配置吗？

**Comment by lm93129** [comment]
映射一个config.yml到/app/conf/config.yml，端口为21114。其他没什么要配置的了，基础的就这些。yml的内容见readme

**Comment by lm93129** [comment]
![image](https://github.com/xiaoyi510/rustdesk-api-server/assets/22451712/57b1f754-a7f4-4000-91c0-5ada9396be71)

如图，由于我是自己构建的镜像，未使用dockerhub上的镜像，自己构建可以先运行make编译，然后运行`docker build -t rustdesk-api-server:latest .`

**Comment by KhyHolyDragon** [comment]
> ![image](https://user-images.githubusercontent.com/22451712/264906767-57b1f754-a7f4-4000-91c0-5ada9396be71.png)
> 
> 如图，由于我是自己构建的镜像，未使用dockerhub上的镜像，自己构建可以先运行make编译，然后运行`docker build -t rustdesk-api-server:latest .`

难道我是因为直接用了docker上的镜像，所以出错了吗？
总是提示请求接口error 404🤣

**Comment by lm93129** [comment]
> > ![image](https://user-images.githubusercontent.com/22451712/264906767-57b1f754-a7f4-4000-91c0-5ada9396be71.png)
> > 如图，由于我是自己构建的镜像，未使用dockerhub上的镜像，自己构建可以先运行make编译，然后运行`docker build -t rustdesk-api-server:latest .`
> 
> 难道我是因为直接用了docker上的镜像，所以出错了吗？ 总是提示请求接口error 404🤣

dockerhub上的镜像可能版本会有点滞后吧，所以自己构建放心点。
