### ISSUE TITLE
我添加API地址后，无法登陆是什么情况啊？请求接口Error 404

### ISSUE THREAD

**Issue by KhyHolyDragon** [xiaoyi510/rustdesk-api-server#17]
大神知道这是什么原因不？谢谢！
![image](https://github.com/xiaoyi510/rustdesk-api-server/assets/140623652/da15246c-f999-4d93-9649-1f25e4000647)
![image](https://github.com/xiaoyi510/rustdesk-api-server/assets/140623652/bd2c09d6-a636-4730-bae4-7f558eeb6f01)

**Comment by lrange2001** [comment]
我也有相同的问题  请问你解决了吗

**Comment by KhyHolyDragon** [comment]
> 我也有相同的问题 请问你解决了吗

没试过了，可能是docker里的源太旧了，可以自己本地编译后再弄应该可以，我看出compose的就是这样做的。

**Comment by KhyHolyDragon** [comment]
> 我也有相同的问题 请问你解决了吗

https://github.com/xiaoyi510/rustdesk-api-server/issues/16

**Comment by lrange2001** [comment]
谢谢，我更换了镜像，尝试后已经可以了  镜像:gb2020/rustdesk-api-server

**Comment by KhyHolyDragon** [comment]
> 谢谢，我更换了镜像，尝试后已经可以了 镜像:gb2020/rustdesk-api-server

谢谢告知，等我需要用的时候我就用他的~
