### ISSUE TITLE
docker hub

### ISSUE THREAD

**Issue by mizb** [xiaoyi510/rustdesk-api-server#18]
大佬，能更新一下docker hub上的版本吗？

**Comment by KhyHolyDragon** [comment]
> 大佬，能更新一下docker hub上的版本吗？

你也报错了吗？

**Comment by mizb** [comment]
> > 大佬，能更新一下docker hub上的版本吗？
> 
> 你也报错了吗？

是的

**Comment by xiaoyi510** [comment]
直接 docker build 一下
