### ISSUE TITLE
android 登录一直显示 failed to access 192.168.31.221:21114

### ISSUE THREAD

**Issue by ntzhuhongbin** [xiaoyi510/rustdesk-api-server#2]
我从rustdesk下载的最新的1.1.9的apk,安装在手机上,使用了您的api server,我使用我的电脑可以使用地址簿了,但是手机上设定了api服务器后,一直无法登录,我看您的api后台一直没有收到请求,是官网的apk有问题吗?

**Comment by andywang1011** [comment]
同样的问题，手机填入API ip:21114，访问失败。
PC使用没有问题

**Comment by jiemo9527** [comment]
+1

**Comment by gisorliu** [comment]
+1

**Comment by xiaoyi510** [comment]
安卓客户端好像不加端口号

**Comment by GMYXDS** [comment]
试试这样的
安卓端不需要填写 http:// 前缀 且必须为 21114 端口

**Comment by xiaoyi510** [comment]
已兼容v1.2部分接口

**Comment by shwatty** [comment]
> 

加不加都一样的提示

**Comment by xiaoyi510** [comment]
截图吧

**Comment by shwatty** [comment]
苹果和安卓客户端都是一样的提示发自我的 iPhone在 2023年6月21日，10:10，vSpear ***@***.***> 写道：﻿
截图吧

**Comment by shwatty** [comment]
![IMG_2436](https://github.com/xiaoyi510/rustdesk-api-server/assets/49614107/8e27d653-0ad2-4038-ae99-4004fc39f42f)
![IMG_2437](https://github.com/xiaoyi510/rustdesk-api-server/assets/49614107/5e3ca166-67db-413d-9d3e-b7daafd96f09)

**Comment by shwatty** [comment]
![IMG_2438](https://github.com/xiaoyi510/rustdesk-api-server/assets/49614107/d35fc767-fb56-4fba-8da8-6137ec4a427f)


21114端口通过浏览器访问是正常的
