### ISSUE TITLE
1.2.2版本不可用

### ISSUE THREAD

**Issue by 3329415183** [xiaoyi510/rustdesk-api-server#20]
请问是什么问题，谢谢！！！

**Comment by xiaoyi510** [comment]
这个还不知道~暂时还没使用这个版本 需要调查下

**Comment by xiaoyi510** [comment]
已经更新了  可以使用了

**Comment by 3329415183** [comment]
非常感谢，我想除了发自内心的感激，已经不能再做什么了



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: vSpear ***@***.***&gt;
发送时间: 2023年10月8日 15:08
收件人: xiaoyi510/rustdesk-api-server ***@***.***&gt;
抄送: 3329415183 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [xiaoyi510/rustdesk-api-server] 1.2.2版本不可用 (Issue #20)





 
已经更新了  可以使用了

**Comment by KhyHolyDragon** [comment]
> 非常感谢，我想除了发自内心的感激，已经不能再做什么了 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: vSpear ***@***.***&gt; 发送时间: 2023年10月8日 15:08 收件人: xiaoyi510/rustdesk-api-server ***@***.***&gt; 抄送: 3329415183 ***@***.***&gt;, Author ***@***.***&gt; 主题: Re: [xiaoyi510/rustdesk-api-server] 1.2.2版本不可用 (Issue #20) 已经更新了 可以使用了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你还可以献身。。。
