### ISSUE TITLE
程序运行报错

### ISSUE THREAD

**Issue by happytrudy** [xiaoyi510/rustdesk-api-server#21]
centos8.0下载rustdesk-api-server_1.4.2_Linux_x86_64.tar.gz

解压后运行 ./rustdesk-api-server

![image](https://github.com/xiaoyi510/rustdesk-api-server/assets/61214170/bae0c369-20de-4ebf-acd8-d922724c65f1)

怎么不报错啊

**Comment by xiaoyi510** [comment]
可以修改配置
使用mysql

**Comment by happytrudy** [comment]
> 可以修改配置 使用mysql

sqllit3不被支持吗
