### ISSUE TITLE
不支持1.2.3和1.2.4的组

### ISSUE THREAD

**Issue by zhangbo8418** [xiaoyi510/rustdesk-api-server#22]
不支持1.2.3和1.2.4的组
![QQ截图20231016100935](https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/e2c0a6b6-8c8c-4a07-8cd8-57a33652a07e)

**Comment by xiaoyi510** [comment]
我看看

**Comment by happytrudy** [comment]
升级这么快吗 我还在1.2.2版本 这要是加个网页就好了

**Comment by QwindF** [comment]
插眼
![image](https://github.com/xiaoyi510/rustdesk-api-server/assets/87116340/30617aef-9505-4ad0-a00a-08a5aef4b47a)

**Comment by xiaoyi510** [comment]
我也还在1.2.2

**Comment by xiaoyi510** [comment]
这个组好像只有展示效果吗? 我先临时上传测试数据了 暂时不知道啥用的

**Comment by zhangbo8418** [comment]
> 这个组好像只有展示效果吗? 我先临时上传测试数据了 暂时不知道啥用的

不知道，我没有Pro版的，听人说Pro版的带控制台，我以为权限分组控制呢。。。

**Comment by zhangbo8418** [comment]
> 这个组好像只有展示效果吗? 我先临时上传测试数据了 暂时不知道啥用的

你看那数据库字段，是不是可以不同用户管理不同分组的客户端呢？

**Comment by xiaoyi510** [comment]
暂时没啥用..
