### ISSUE TITLE
接口返回的设备信息无法写入到MySQL表中

### ISSUE THREAD

**Issue by MrChenhtlss** [xiaoyi510/rustdesk-api-server#23]
`rustdesk-api-server  | 2023/10/18 23:39:09 请求接口 /api/sysinfo POST {"cpu":"Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz, 3.22GHz, 4/4 cores","hostname":"admin-pc","id":"666666","memory":"7.92GB","os":"windows / Windows 7 Enterprise - 0 (7601)","username":"admin","uuid":"ZDc0NGU3MmQyYS00YmYwLWE2OWUtMTk0NjBjODlkY2Q0","version":"1.2.4"`

![WeChat39a3b80853f1fa748a54220bc0720939](https://github.com/xiaoyi510/rustdesk-api-server/assets/146620104/3c7a8c8c-210a-44a3-873c-80ef6460e805)

![WeChat2f0d1694334e0631628e78e9c6023aeb](https://github.com/xiaoyi510/rustdesk-api-server/assets/146620104/1d169812-7c60-49e8-a9cd-7e22529a74c5)

![WechatIMG504](https://github.com/xiaoyi510/rustdesk-api-server/assets/146620104/95609059-ca2f-4a18-9169-796b627765d8)

![5051697644047_ pic_副本](https://github.com/xiaoyi510/rustdesk-api-server/assets/146620104/87e38330-283c-40a5-b2ad-6b17532d87a2)

接口有返回hostname username  platform 以及硬件信息但是没有写到表里

**Comment by xiaoyi510** [comment]
1

**Comment by MrChenhtlss** [comment]
> 1

终于等到你，还好我又没放弃！！
算了唱不下去了！！！

**Comment by xiaoyi510** [comment]
这个有啥用吗

**Comment by MrChenhtlss** [comment]
> 这有啥用吗

它可以让我快速了解主机的硬件信息 系统类型 主机名 用户名
这些信息对我非常有帮助！！！

现在我添加一台主机都需要进入数据库手动把缺少的信息手动补齐，这非常不便利！

**Comment by zhangbo8418** [comment]
> > 这有啥用吗
> 
> 它可以让我快速了解主机的硬件信息 系统类型 主机名 用户名 这些信息对我非常有帮助！！！
> 
> 现在我添加一台主机都需要进入数据库手动把缺少的信息手动补齐，这非常不便利！

我直接用的sqlite3，好像没这问题。。。

**Comment by zhangbo8418** [comment]
> > 这有啥用吗
> 
> 它可以让我快速了解主机的硬件信息 系统类型 主机名 用户名 这些信息对我非常有帮助！！！
> 
> 现在我添加一台主机都需要进入数据库手动把缺少的信息手动补齐，这非常不便利！

![QQ截图20231023180043](https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/5e985836-4f69-4380-8f16-31cbef123a82)

**Comment by MrChenhtlss** [comment]
> > > 这有啥用吗
> > 
> > 
> > 它可以让我快速了解主机的硬件信息 系统类型 主机名 用户名 这些信息对我非常有帮助！！！
> > 现在我添加一个主机都需要进入数据库手动把缺少的信息手动补齐，这非常不方便！
> 
> ![QQ截图20231023180043](https://user-images.githubusercontent.com/46797568/277300196-5e985836-4f69-4380-8f16-31cbef123a82.png)

非常感谢你您回复，但是目前使用mysql遇到了这样的问题！

因为我的设备主要主要是Windows居多，其次Linux，Android，MacOS，mysql

使用mysql方便管理和增量备份

请问您是自己编译的客户端还是？使用的是Flutter版本还是Sciter？

**Comment by zhangbo8418** [comment]
> 这个有啥用吗

硬件信息确实没啥用，客户端不会显示，但是hash是密码，同步密码是有用的，还有就是平台什么的也是有用的，会同步到客户端显示的。。。
![QQ截图20231023180724](https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/44e2be1d-89ed-4214-b660-d6de5e552bca)

**Comment by MrChenhtlss** [comment]
> > 这有啥用吗
> 
> 硬件信息确实没啥用，客户端不会显示，但是hash是密码，同步密码是有用的，还有平台什么的也是有用的，会同步到客户端显示的。。。 ![QQ截图20231023180724](https://user-images.githubusercontent.com/46797568/277301978-44e2be1d-89ed-4214-b660-d6de5e552bca.png)

硬件信息对我帮助非常大，因为我的设备数量庞大可以便看到每个主机的信息，哪怕Rustdesk无法显示，主要是平台信息这样可以方便定位和管理

**Comment by zhangbo8418** [comment]
> > > > 这有啥用吗
> > > 
> > > 
> > > 它可以让我快速了解主机的硬件信息 系统类型 主机名 用户名 这些信息对我非常有帮助！！！
> > > 现在我添加一个主机都需要进入数据库手动把缺少的信息手动补齐，这非常不方便！
> > 
> > 
> > ![QQ截图20231023180043](https://user-images.githubusercontent.com/46797568/277300196-5e985836-4f69-4380-8f16-31cbef123a82.png)
> 
> 非常感谢你您回复，但是目前使用mysql遇到了这样的问题！
> 
> 因为我的设备主要主要是Windows居多，其次Linux，Android，MacOS，mysql
> 
> 使用mysql方便管理和增量备份
> 
> 请问您是自己编译的客户端还是？使用的是Flutter版本还是Sciter？

服务端和客户端我也是根据自己的需求简单的改了下，因为我是群晖做的服务器所以我还写了个UI。。。
![QQ截图20231023181133](https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/1ac41b07-18e5-4f96-abd3-5e84ed4dfaaf)
![QQ截图20231023181201](https://github.com/xiaoyi510/rustdesk-api-server/assets/46797568/71252dcf-5a8a-459c-9c82-ef9a3b1aec32)

**Comment by MrChenhtlss** [comment]
> > > > > 这有啥用吗
> > > > 
> > > > 
> > > > 它可以让我快速了解主机的硬件信息 系统类型 主机名 用户名 这些信息对我非常有帮助！！！现在
> > > > 我添加一个主机都需要进入数据库手动把所需的信息手动补齐，这非常不方便！
> > > 
> > > 
> > > ![QQ截图20231023180043](https://user-images.githubusercontent.com/46797568/277300196-5e985836-4f69-4380-8f16-31cbef123a82.png)
> > 
> > 
> > 非常感谢您的回复，但是目前使用mysql遇到了这样的问题！
> > 因为我的设备主要是Windows居多，其次是Linux，Android，MacOS，mysql
> > 使用mysql方便管理和增量备份
> > 请问您是自己编译的客户端还是？使用的是 Flutter 版本还是 Sciter？
> 
> 服务端和客户端我也是根据自己的需求简单的改了下，因为我是群晖做的服务器所以我还写了个UI。。。 ![QQ截图20231023181133](https://user-images.githubusercontent.com/46797568/277303915-1ac41b07-18e5-4f96-abd3-5e84ed4dfaaf.png) ![QQ截图20231023181201](https://user-images.githubusercontent.com/46797568/277303944-71252dcf-5a8a-459c-9c82-ef9a3b1aec32.png)



> > > > > 这有啥用吗
> > > > 
> > > > 
> > > > 它可以让我快速了解主机的硬件信息 系统类型 主机名 用户名 这些信息对我非常有帮助！！！
> > > > 现在我添加一个主机都需要进入数据库手动把缺少的信息手动补齐，这非常不方便！
> > > 
> > > 
> > > ![QQ截图20231023180043](https://user-images.githubusercontent.com/46797568/277300196-5e985836-4f69-4380-8f16-31cbef123a82.png)
> > 
> > 
> > 非常感谢你您回复，但是目前使用mysql遇到了这样的问题！
> > 因为我的设备主要主要是Windows居多，其次Linux，Android，MacOS，mysql
> > 使用mysql方便管理和增量备份
> > 请问您是自己编译的客户端还是？使用的是Flutter版本还是Sciter？
> 
> 服务端和客户端我也是根据自己的需求简单的改了下，因为我是群晖做的服务器所以我还写了个UI。。。 ![QQ截图20231023181133](https://user-images.githubusercontent.com/46797568/277303915-1ac41b07-18e5-4f96-abd3-5e84ed4dfaaf.png) ![QQ截图20231023181201](https://user-images.githubusercontent.com/46797568/277303944-71252dcf-5a8a-459c-9c82-ef9a3b1aec32.png)

好的!
非常感谢！

**Comment by xiaoyi510** [comment]
emm 空了我看看 因为我个人使用密码都是自己记住的,名字也是改的,暂时还没用到你的使用场景

**Comment by MrChenhtlss** [comment]
> emm 空了我看看 因为我个人使用密码都是自己记住的,名字也是改的,暂时还没用到你的使用场景

好的，持续在线等待您的消息！

**Comment by zhangbo8418** [comment]
> > > 这有啥用吗
> > 
> > 
> > 硬件信息确实没啥用，客户端不会显示，但是hash是密码，同步密码是有用的，还有平台什么的也是有用的，会同步到客户端显示的。。。 ![QQ截图20231023180724](https://user-images.githubusercontent.com/46797568/277301978-44e2be1d-89ed-4214-b660-d6de5e552bca.png)
> 
> 硬件信息对我帮助非常大，因为我的设备数量庞大可以便看到每个主机的信息，哪怕Rustdesk无法显示，主要是平台信息这样可以方便定位和管理

你那不是硬件信息，硬件信息是CPU啥的，我用sqlite3没你那问题，hostname（主机名） username（用户名） hash（密码） platform（平台） 都能同步。。。。可能是使用mysql特有问题吧。。。

**Comment by MrChenhtlss** [comment]
> hash

接口有硬件信息(CPU,内存。。。)返回的，但是表里边没有对应的字段，sqlite3对我场景不适用

**Comment by MrChenhtlss** [comment]
> 你那不是硬件信息，硬件信息是CPU啥的，我用sqlite3没你那问题，hostname（主机名） username（用户名） hash（密码） platform（平台） 都能同步。。。。可能是使用mysql特有问题吧。。。

假设我更换为sqlite3，我该如何配置它运行起来？需要手动创建一个名为sqlite.db的库文件以及在conf/config.yml中指定这个库文件的路径么？！

**Comment by xiaoyi510** [comment]
sqlite 需要自己cgo 编译下

**Comment by MrChenhtlss** [comment]
1

vSpear ***@***.***>于2023年11月14日 周二17:56写道：
