### ISSUE TITLE
 go-sqlite3 requires cgo to work. This is a stub

### ISSUE THREAD

**Issue by sun9999-dev** [xiaoyi510/rustdesk-api-server#24]
2023/10/22 11:17:03.282 [I] [mysql.go:40]  数据库注册类型 sqlite3
[ORM]2023/10/22 11:17:03 register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2023/10/22 11:17:03.282 [E] [mysql.go:49]  sqlite3 数据库注册失败 register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

**Comment by xiaoyi510** [comment]
你可以使用 mysql 嘿嘿 使用sqlite 需要自己cgo 编译下
