### ISSUE TITLE
docker成功部署后如何重命名设备

### ISSUE THREAD

**Issue by kokojacket** [xiaoyi510/rustdesk-api-server#26]
你好，我使用docker成功部署后，发现默认显示的本号归属无法重命名，刷新后会重新重置
![image](https://github.com/xiaoyi510/rustdesk-api-server/assets/74887370/c16c2210-dcb0-47ef-bf75-f73776264fb3)

**Comment by MrChenhtlss** [comment]
您好，可以尝试修改源代码重新编译

**Comment by Sunev** [comment]
这是因为本账号下的设备信息储存在 rustdesk_token 表里面，此表没有保存 Alias 信息。
要保存重命名的信息，需要改表结构

**Comment by xiaoyi510** [comment]
你们写了可以提一个pr吗 哥哥们

**Comment by Sunev** [comment]
我的直觉告诉我，你没写这个功能，应该是自建的hbbs可以自定义设备ID吧？所以你没这需求。。我觉得这样也行

**Comment by xiaoyi510** [comment]
这rustdesk写的API真是骂娘....结构千奇百怪的 原来重命名是有效的

**Comment by MrChenhtlss** [comment]
出现什么问题了么，近期要打算fork rustdesk的代码重新编译最新的版本投入使用

vSpear ***@***.***>于2024年2月28日 周三10:20写道：

**Comment by kokojacket** [comment]
已解决，使用了另外一个大佬的项目。可以相互参考一下
https://github.com/kingmo888/rustdesk-api-server
