### ISSUE TITLE
最新版导入标签失败

### ISSUE THREAD

**Issue by JunXiaoRuo** [xiaoyi510/rustdesk-api-server#30]
![af7ba79f1578aa6864706ba23e3edd5e](https://github.com/xiaoyi510/rustdesk-api-server/assets/47996900/2d367ce2-ad36-4d51-a799-7fcaabe90c0d)
![04ca8bd3a70b878a39d76ca180422cf7](https://github.com/xiaoyi510/rustdesk-api-server/assets/47996900/dc51aeb2-f794-45c8-a0f5-e8bf2bc668ce)
![9cbfabcf1d040b80dfe30e1966fc05c8](https://github.com/xiaoyi510/rustdesk-api-server/assets/47996900/63c0abfc-a4aa-44cd-8016-9042c2d4da84)

**Comment by JunXiaoRuo** [comment]
![image](https://github.com/xiaoyi510/rustdesk-api-server/assets/47996900/9e561444-d335-4a6b-a383-ba4c533c777d)

**Comment by xiaoyi510** [comment]
好家伙 这破接口设计的

**Comment by JunXiaoRuo** [comment]
> 好家伙 这破接口设计的

好像是最新版的更新了数据传输哈哈哈

**Comment by pope-L** [comment]
代码自行编译是正常的，现在142版不是最新的
