### ISSUE TITLE
api-server 运行错误该如何解决呢

### ISSUE THREAD

**Issue by pope-L** [xiaoyi510/rustdesk-api-server#32]
ORM]2024/02/06 13:12:00 register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub
2024/02/06 13:12:00.901 [E] [mysql.go:49]  sqlite3 数据库注册失败 register db Ping `default`, Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work. This is a stub

**Comment by pope-L** [comment]
自己编译了，没设cgo_enable=0
ubuntu 20 go1.18
[rustdesk-api-server1.zip](https://github.com/xiaoyi510/rustdesk-api-server/files/14199931/rustdesk-api-server1.zip)
可以在我的centos6下运行了 感谢作者

**Comment by MrChenhtlss** [comment]
可以请教编译的方法和过程么
