### ISSUE TITLE
Login failed on "nightly" version

### ISSUE THREAD

**Issue by gisorliu** [xiaoyi510/rustdesk-api-server#5]
![image](https://user-images.githubusercontent.com/43399455/216486917-a30acd25-a06d-4fe7-98e3-7e1f84a0c1aa.png)

**Comment by xiaoyi510** [comment]
ok

**Comment by GMYXDS** [comment]
> ![image](https://user-images.githubusercontent.com/43399455/216486917-a30acd25-a06d-4fe7-98e3-7e1f84a0c1aa.png)

看看这个：https://github.com/GMYXDS/rustdesk-api-server

**Comment by xiaoyi510** [comment]
已兼容v1.2部分接口
