### ISSUE TITLE
官方又更新了 版本现在登录不了了

### ISSUE THREAD

**Issue by iamckun** [xiaoyi510/rustdesk-api-server#7]
官方又更新了 版本现在登录不了了

**Comment by xiaoyi510** [comment]
哈哈哈

**Comment by xiaoyi510** [comment]
官方不是 1.1.9 吗 好像没更新啊

**Comment by iamckun** [comment]
1.2了uI都改了

**Comment by GMYXDS** [comment]
> 官方不是 1.1.9 吗 好像没更新啊

最新release 里面，最上面有个nightly版本，是1.2.0的发布版本。1.2.0的界面进行了大改，可能api接口也改了？
