### ISSUE TITLE
官方不是 1.1.9 吗 好像没更新啊

### ISSUE THREAD

**Issue by iamckun** [xiaoyi510/rustdesk-api-server#8]
官方不是 1.1.9 吗 好像没更新啊

_Originally posted by @xiaoyi510 in https://github.com/xiaoyi510/rustdesk-api-server/issues/7#issuecomment-1439475833_
            升级了现在1.2了UI都改了还挺好看

**Comment by xiaoyi510** [comment]
好的 我去了解下
