### ISSUE TITLE
rustdesk api server地址簿无法长期保存账号信息

### ISSUE THREAD

**Issue by wanglei52076** [xiaoyi510/rustdesk-api-server#9]
按这个搭建的api server，采用mysql 8.0.31-debian版本（最新版应该有bug），注册账户登陆都没有问题，但是过几个小时就要重新登陆，无法长期保存，不知道哪里需要调整？

**Comment by GMYXDS** [comment]
调整acesstoken的有效时间

**Comment by wanglei52076** [comment]
能具体说说怎么调整吗？我用Navicat连接数据库后修改acess_token的expire_time时间，但是仍然几个小时候失效，需要退出重新登陆！

**Comment by GMYXDS** [comment]
> 能具体说说怎么调整吗？我用Navicat连接数据库后修改acess_token的expire_time时间，但是仍然几个小时候失效，需要退出重新登陆！

我没这个问题，会一直保持登录啊，只要token没发送变化

**Comment by wanglei52076** [comment]
acess_token确实会变，重新登陆会获取新的acess_token，有固定方向吗？

**Comment by GMYXDS** [comment]
不知道，我的没变。我自己用python实现了一版，登录保持不变就行了，只要不重复登录就行

**Comment by GMYXDS** [comment]
后面我会开源，你可以关注一下

**Comment by wanglei52076** [comment]
好的 谢谢！

**Comment by GMYXDS** [comment]
> 好的 谢谢！

https://github.com/GMYXDS/rustdesk-api-server
